kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: todolist-cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        # Port 80 is already used on the Application EC2 host.
        hostPort: 8081
      - containerPort: 443
        hostPort: 8444
